"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = '>>'

[aws]
disabled = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmd_duration]
min_time = 5000

[package]
disabled = true